shallow_clone: true
clone_depth: 2
skip_tags: false
max_jobs: 21

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  fast_finish: true
  matrix:
    - PYTHON: C:\Python36
      WHEEL_PLATFORM: win32
    - PYTHON: C:\Python36-x64
      EXTRA_CMAKE_ARGS: -DCMAKE_GENERATOR_PLATFORM=x64
      WHEEL_PLATFORM: win_amd64

install:
  # Install dependencies
  - set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
  - python -m pip install -U pip setuptools wheel
  - python -m pip install --only-binary=all --pre scipy scikit-learn

  # Build and install from wheel so we see this works
  - python setup.py build_ext --cmake-args=%EXTRA_CMAKE_ARGS% bdist_wheel
  # Rename the wheel to contain PEP-425 platform tags
  - ps: mv dist\*.whl dist\MulticoreTSNE-$(python -c 'from setup import VERSION; print(VERSION)')-py27.py3-none-$env:WHEEL_PLATFORM.whl
  - FOR /F %%a IN ('dir /b dist\\*.whl') DO (SET "wheel=dist\\%%a")

  - python -m pip install %wheel%
  - python -m pip install -U --no-deps %wheel%

build: off

test_script:
  - pushd .. & python -m unittest discover -v MulticoreTSNE & popd

artifacts:
  - path: 'dist\*.whl'
    name: wheel
