branches:
  only:
    - dev-win

shallow_clone: true
clone_depth: 2
skip_tags: false
#skip_non_tags: true
max_jobs: 21

environment:
  fast_finish: true
  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools wheel"
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe -m pip install -v --no-deps ."
  - "%PYTHON%\\python.exe -m pip install --pre scipy scikit-learn"

build: off

test_script:
  - "pushd .. & %PYTHON%\\python.exe -m unittest discover MulticoreTSNE.tests & popd"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

#artifacts:
#  # bdist_wheel puts your built wheel in the dist directory
#  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
